force-app/main/default/objects/Case/fields/External_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Site_Id__c</fullName>
    <defaultValue>$Label.TECH_TBL_JP_EXTERNAL_SITE_ID</defaultValue>
    <label>External Site Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/External_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Site_Id__c</fullName>
    <defaultValue>$Label.TECH_TBL_JP_EXTERNAL_SITE_ID</defaultValue>
    <label>External Site Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>245</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataFactory_Test.cls
@isTest
global without sharing class DataFactory_Test{
    public static LiveChatVisitor createLiveChatVisitor() {
        LiveChatVisitor chatVisitor = new LiveChatVisitor();

        insert chatVisitor;
        return chatVisitor;
    }

    public static LiveChatTranscript createLiveChatTranscript(Id chatVisitorId) {
        LiveChatTranscript transcript = new LiveChatTranscript(
            First_Name__c = 'Duy',
            Last_Name__c = 'Huynh',
            Email_Address__c = 'duy.huynh@yopmail.com',
            Subject__c = 'Test Subject',
            External_Site_Id__c = 'tbl-jp',
            LiveChatVisitorId = chatVisitorId
        );

        insert transcript;
        return transcript;
    }

    public static List<Case> createCases() {
        List<Case> listCase = new List<Case>();
        Case tmpCase = new Case(
            Subject = 'Case 001'
        );

        Case tmpCase2 = new Case(
            Subject = 'Case 002'
        );

        listCase.Add(tmpCase);
        listCase.Add(tmpCase2);
        insert listCase;
        return listCase;
    }

    // public static List<EmailMessage> createEmailMessages(Id caseId) {
    //     List<EmailMessage> listEmailMessage = new List<EmailMessage>();
    //     EmailMessage em = new EmailMessage(
    //         Subject = 'Case 001',
    //         Incoming = true,
    //         ParentId = caseId
    //     );
    //     listEmailMessage.Add(em);
    //     insert listEmailMessage;
    //     return listEmailMessage;
    // }
}