force-app/main/default/objects/Case/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <label>Last Modified By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CaseSelector.cls
/*------------------------------------------------------------
Author:        Duy Huynh
Company:       Merkle
Description:   A utility class for getting data from Case Object
Test Class:    N/A
History
<Date>      <Authors Name>     <Brief Description of Change>
2022/12/02     Duy Huynh        Init
------------------------------------------------------------*/
public without sharing class CaseSelector {
    public static List<Case> getListCaseByIds(List<Id> listCaseId){
        List<Case> listCaseUpdating = new List<Case>();

        listCaseUpdating = [select Last_Modified_By__c, Last_Modified_Date__c
                            from Case 
                            where Id IN :listCaseId];
        if(!listCaseUpdating.isEmpty()) {
            return listCaseUpdating;
        }
        return null;
    }
}