force-app/main/default/objects/Case/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <label>Last Modified By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/*------------------------------------------------------------
+Author:        Duy Huynh
Company:        Merkle
Description:    
Test Class:     CaseTriggerHandler_Test
History
<Date>          <Authors Name>          <Brief Description of Change>
2022/12/01        Duy Huynh         	    Init
------------------------------------------------------------*/
public class CaseTriggerHandler extends TriggerHandler {
    public CaseTriggerHandler(){}

    public override void beforeUpdate() {
        updateLastModified();
    }

    public static void updateLastModified () {
        List<User> listUser = new List<User>();
        String caseId = '';
        List<Id> listCaseId = new List<Id>();
        String userId = UserInfo.getUserId();

        for(Case tmpCase : (List<Case>)Trigger.New) {
            listCaseId.Add(tmpCase.Id);
        }
                            
        listUser = UserSelector.getListUserByIds(userId);

        if(listUser != null) {
            for(Case tmpCase : (List<Case>)Trigger.New) {
                if(CheckRecursive.isUpdatedCase == false) {
                    tmpCase.Last_Modified_Date__c = System.now();
                    tmpCase.Last_Modified_By__c = listUser[0].LastName + ' ' + listUser[0].FirstName;
                }
            }
        }
    }
}