force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/External_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Site_Id__c</fullName>
    <defaultValue>$Label.TECH_TBL_JP_EXTERNAL_SITE_ID</defaultValue>
    <label>External Site Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>245</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Chatbot_CheckWithinBusinessHours_Test.cls
@IsTest
public with sharing class Chatbot_CheckWithinBusinessHours_Test {
    @TestSetup
    public static void setupData() {
        LiveChatVisitor chatVisitor = DataFactory_Test.createLiveChatVisitor();
        LiveChatTranscript transcriptRecords = DataFactory_Test.createLiveChatTranscript(chatVisitor.Id);
    }

    @IsTest
    static void testInBusinessHours() {
        List<LiveChatTranscript> transcriptRecords = [SELECT Id, Name, First_Name__c, Last_Name__c, Email_Address__c, Subject__c, External_Site_Id__c, CreatedDate
                                                        FROM LiveChatTranscript
                                                        LIMIT 1];
        Chatbot_CheckWithinBusinessHours.TranscriptInput trsInput = new Chatbot_CheckWithinBusinessHours.TranscriptInput();
        trsInput.routableID = transcriptRecords[0].Id;
        List<Chatbot_CheckWithinBusinessHours.TranscriptInput> trsInputList = new List<Chatbot_CheckWithinBusinessHours.TranscriptInput>{trsInput};
        Boolean isInBH = true;

        Test.startTest();
        List<Boolean> isInBHList = Chatbot_CheckWithinBusinessHours.isWithInBusinessHours(trsInputList);
        Test.stopTest();

        isInBH = isInBHList[0];

        if(!isInBH) {
            System.AssertEquals(false, isInBH);
        }else {
            System.AssertEquals(true, isInBH);
        }
    }
}